# Generated by Django 4.2.24 on 2025-09-24 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadPeticionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('dias_plazo', models.IntegerField(help_text='Plazo en días hábiles para la respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(max_length=50, unique=True)),
                ('asunto', models.TextField()),
                ('fecha_recepcion_inicial', models.DateField()),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('respuesta_tramite', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('Asignado', 'Asignado'), ('En Trámite', 'En Trámite'), ('Por Vencer', 'Por Vencer'), ('Vencido', 'Vencido'), ('Resuelto', 'Resuelto')], default='Recibido', max_length=20)),
                ('peticionario_nombre', models.CharField(max_length=255)),
                ('peticionario_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calidad_peticionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.calidadpeticionario')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_tramite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.tipotramite')),
            ],
        ),
    ]
