# Generated by Django 4.2.24 on 2025-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('En Trámite', 'En Trámite'), ('Resuelto', 'Resuelto')], default='Recibido', max_length=20),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
