# Generated by Django 4.2.24 on 2025-09-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_alter_pqrs_estado_alter_pqrs_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('En Trámite', 'En Trámite'), ('Resuelto', 'Resuelto'), ('Anulado', 'Anulado')], default='Recibido', max_length=20),
        ),
    ]
