# Generated by Django 4.2.24 on 2025-09-25 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_alter_pqrs_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos_pqrs/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Cédula, Derecho de petición, etc.', max_length=255, null=True)),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='nucleo.pqrs')),
            ],
        ),
    ]
