# Generated by Django 4.2.24 on 2025-09-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_archivoadjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoadjunto',
            name='tipo_archivo',
            field=models.CharField(choices=[('INTERNO', 'Documento de Soporte Interno'), ('PETICIONARIO', 'Anexo del Peticionario')], default='INTERNO', max_length=20),
        ),
    ]
