# Generated by Django 4.2.24 on 2025-09-27 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0005_archivoadjunto_tipo_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(verbose_name='Nota de Seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='nucleo.pqrs')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
