# Generated by Django 4.2.24 on 2025-09-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre Definitivo'),
        ),
    ]
