# Generated by Django 4.2.24 on 2025-09-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_pqrs_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='dependencia_trasladada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dependencia a la que se traslada'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='estado_traslado',
            field=models.CharField(choices=[('Activo', 'Activo en Vicerrectoría'), ('En Traslado', 'En Traslado a Otra Dependencia')], default='Activo', max_length=20),
        ),
    ]
