# Generated by Django 4.2.24 on 2025-09-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_pqrs_dependencia_trasladada_pqrs_estado_traslado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='confirmado',
            field=models.BooleanField(default=True, help_text='Indica si la PQRS ha sido revisada y confirmada por un coordinador.'),
        ),
    ]
