# Generated by Django 5.0.6 on 2025-10-06 20:15
from django.db import migrations
import os

def crea_superusuario(apps, schema_editor):
    from django.contrib.auth.models import User
    
    # Lee las credenciales desde variables de entorno o usa valores por defecto
    DJANGO_SUPERUSER_USERNAME = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
    DJANGO_SUPERUSER_PASSWORD = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'admin12345')
    DJANGO_SUPERUSER_EMAIL = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@example.com')
    
    # Crea el superusuario solo si no existe
    if not User.objects.filter(username=DJANGO_SUPERUSER_USERNAME).exists():
        User.objects.create_superuser(
            username=DJANGO_SUPERUSER_USERNAME,
            password=DJANGO_SUPERUSER_PASSWORD,
            email=DJANGO_SUPERUSER_EMAIL
        )
        print(f'\nSuperusuario {DJANGO_SUPERUSER_USERNAME} creado.')
    else:
        print(f'\nSuperusuario {DJANGO_SUPERUSER_USERNAME} ya existe.')


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_pqrs_confirmado'), # ¡IMPORTANTE! Revisa que este sea el nombre de tu migración anterior.
    ]

    operations = [
        migrations.RunPython(crea_superusuario),
    ]